name: Build and Release Datapack

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0, v2.3, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Zip
      run: |
        mkdir -p build
        zip -r build/datapack.zip content/*

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Automatic release for datapack version ${{ github.ref_name }}.
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: build/datapack.zip
        asset_name: datapack.zip
        asset_content_type: application/zip
